### ISSUE TITLE
Cone_finder won't run from launch file

### ISSUE THREAD

**Issue by pryme** [ProgrammingRobotsStudyGroup/TrafficConeFinderCode#3]
I can run cone_finder ok using `rosrun cone_finder detect_cones.py -r &`. However when I try to run it from a launch file it causes an error. Perhaps I am doing something wrong in the launch file? 
##### Launch file
    robot@Victoria:~/catkin_ws/src/launch$ cat demo_launch.launch 
    <launch>
      <include file="$(find realsense_camera)/launch/r200_nodelet_default.launch" />
      <node name="cone_finder" pkg="cone_finder" output="screen" type="detect_cones.py" args="-r" />
      <node name="image_view" pkg="image_view" type="image_view" args="image:=/cone_finder/colorImage" output="screen" />

    </launch>

##### Error text
    usage: detect_cones.py [-h] [--use_ros_topic] [--image_dir IMAGE_DIR]
                           [--debug]
                           [video_file]
    detect_cones.py: error: unrecognized arguments: __log:=/home/robot/.ros/log/dee00a72-f397-11e6-8f41-000f6004684f/cone_finder-4.log
    init done
    [cone_finder-4] process has died [pid 2270, exit code 2, cmd /home/robot/catkin_ws/src/TrafficConeFinderCode/scripts/detect_cones.py -r __name:=cone_finder  __log:=/home/robot/.ros/log/dee00a72-f397-11e6-8f41-000f6004684f/cone_finder-4.log].
    log file: /home/robot/.ros/log/dee00a72-f397-11e6-8f41-000f6004684f/cone_finder-4*.log

**Comment by binary-bard** [comment]
I am guessing that this is because there is no processing of ros arguments. I'll look into it.

**Comment by binary-bard** [comment]
Shouldn't closed yet

**Comment by binary-bard** [comment]
Ok, I added a fix that will process ros argument so it shouldn't error out. Please try the launch script again.

**Comment by pryme** [comment]
Tested - worked for me. Closing.

**Comment by jmdahling** [comment]
Fixed by https://github.com/ProgrammingRobotsStudyGroup/TrafficConeFinderCode/commit/ae0493264b9a4a4434964fd09b5b148b5bb2c44c
